// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Atlas(arg1) {
  return window['go']['main']['App']['Atlas'](arg1);
}

export function GetInfo(arg1, arg2) {
  return window['go']['main']['App']['GetInfo'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
