// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Atlas(arg1:string):Promise<main.AtlasDocuments>;

export function GetInfo(arg1:Array<string>,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;
